project_id = "gbuvtzqqzyiytypenzae"

[functions.alfie-chat-widget]
verify_jwt = true

[functions.request-password-reset]
verify_jwt = false

[functions.create-ambassadeur-coupon]
verify_jwt = false

[functions.admin-stripe-coupons]
verify_jwt = true

[functions.animate-image]
verify_jwt = true

[functions.alfie-generate-texts]
verify_jwt = true

[functions.request-affiliate-payout]
verify_jwt = true

[functions.stripe-connect-onboard]
verify_jwt = true

[functions.stripe-connect-refresh]
verify_jwt = true

[functions.stripe-connect-dashboard]
verify_jwt = true

[functions.stripe-connect-webhook]
verify_jwt = false

[functions.admin-process-affiliate-payout]
verify_jwt = true
